name: 'whas_weather_data_platform'
version: '1.0.0'
config-version: 2

profile: 'whas_weather_data_platform'

model-paths:
  - models
test-paths:
  - tests

models:
  whas_weather_data_platform:

    staging:
      +schema: 'weather_staging'
      +materialized: view
      
      daily_forecast:
        +tags:
          - 'daily_forecast'

      hourly_forecast:
        +tags:
          - 'hourly_forecast'

      observation:
        +tags:
          - observation

    marts:
      +schema: 'weather_mart'
      +materialized: table
