name: CICD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "597341305438"

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --group dev --group scrape

      - parallel:

        - name: Check Python lint
          run: uv run poe py-check-lint
  
        - name: Check Python format
          run: uv run poe py-check-format
  
        - name: Check Python types
          run: uv run poe py-check-types
  
        - name: Check SQL lint
          run: uv run poe sql-check-lint
  
        - name: Measure test coverage
          run: uv run poe coverage
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: "arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ github.event.repository.name }}-github-actions-role"
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push scraper image
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          REPOSITORY: whas-weather/scrape
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f containers/scrape/Dockerfile -t "$REGISTRY/$REPOSITORY:$IMAGE_TAG" .
          docker push "$REGISTRY/$REPOSITORY:$IMAGE_TAG"

      - name: Build and push dbt image
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          REPOSITORY: whas-weather/dbt-build
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f containers/dbt/Dockerfile -t "$REGISTRY/$REPOSITORY:$IMAGE_TAG" .
          docker push "$REGISTRY/$REPOSITORY:$IMAGE_TAG"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: |
          terraform apply \
            -auto-approve \
            -var="image_tag=${{ github.sha }}"
