name: CICD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 597341305438

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@10.1.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --group dev --group scrape

      - name: Check Python lint
        run: uv run poe py-check-lint
        background: true

      - name: Check Python format
        run: uv run poe py-check-format
        background: true

      - name: Check Python types
        run: uv run poe py-check-types
        background: true

      - name: Check SQL lint
        run: uv run poe sql-check-lint
        background: true

      - name: Measure test coverage
        run: uv run poe coverage
        background: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: "arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ github.event.repository.name }}-github-actions-role"
          aws-region: ${{ env.AWS_REGION }}

      - name: Get AWS identity
        run: aws sts get-caller-identity
